# Generated by Django 4.2 on 2023-05-03 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "members",
                    models.ManyToManyField(
                        null=True,
                        related_name="teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("Green", "Green"),
                            ("Amber", "Amber"),
                            ("Red", "Red"),
                        ],
                        default="Green",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("Green", "Green"),
                            ("Amber", "Amber"),
                            ("Red", "Red"),
                        ],
                        default="Green",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "cost",
                    models.CharField(
                        choices=[
                            ("Green", "Green"),
                            ("Amber", "Amber"),
                            ("Red", "Red"),
                        ],
                        default="Green",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("update", models.TextField(null=True)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="tag",
            field=models.ManyToManyField(
                null=True, related_name="p_tags", to="projects.projecttag"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_members",
                to="projects.team",
            ),
        ),
    ]
