# Generated by Django 4.2 on 2023-05-04 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_project_tag_alter_project_team_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectTag",
            new_name="ProjectCategory",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="tag",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="projectcategory",
            old_name="tag",
            new_name="name",
        ),
    ]
