# Generated by Django 4.2 on 2023-05-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_tasktag_task_status_task_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tag",
            field=models.ManyToManyField(
                related_name="tasks", to="tasks.tasktag"
            ),
        ),
    ]
