# Generated by Django 4.2 on 2023-05-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_alter_task_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasktag",
            old_name="tag",
            new_name="name",
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Urgent", "Urgent"),
                    ("High", "High"),
                    ("Moderate", "Moderate"),
                    ("Low", "Low"),
                    ("-", "Blank"),
                ],
                default="-",
                max_length=200,
                null=True,
            ),
        ),
    ]
