# Generated by Django 4.2 on 2023-05-04 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_rename_projecttag_projectcategory_and_more"),
        ("tasks", "0006_rename_tag_tasktag_name_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="projects.projectcategory",
            ),
        ),
    ]
